### ISSUE TITLE
500 Internal Privoxy Error

### ISSUE THREAD

**Issue by angcyo** [simonpercic/OkLog#21]
500 Internal Privoxy Error

Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

**Comment by simonpercic** [comment]
@angcyo , I assume this is the error you saw once you have clicked on the OkLog-generated link, correct?

I would assume this is an internal and temporary error by the default hosting provider, OpenShift by Red Hat.

Can this issue be reproduced? Please provide the OkLog-generated link that caused the error so I can investigate further.
