### ISSUE TITLE
Empty response body

### ISSUE THREAD

**Issue by artemkopan** [simonpercic/OkLog#24]
Please check this request
https://goo.gl/HWovyt

**Comment by simonpercic** [comment]
Hi, I have tried to reproduce the issue by calling the same endpoint as in your example. 

It seems like the response body is too large for Android's logging system, see [known limitations](https://github.com/simonpercic/OkLog#known-limitations)

The only solution is to copy both OkLog logcat lines into a single URL and open it in a browser.
