### ISSUE TITLE
Notice: http://responseecho-simonpercic.rhcloud.com/ URLs no longer working

### ISSUE THREAD

**Issue by simonpercic** [simonpercic/OkLog#32]
## Important - Update notice
ResponseEcho (the server-side component of OkLog) was available at `responseecho-simonpercic.rhcloud.com`, which will **no longer be available**.   
It is now available at `oklog.responseecho.com`.

To prevent OkLog-generated URLs from breaking, **update your version of OkLog to 2.2.0** OR call **`setBaseUrl`** with the new URL:
```java
setBaseUrl("http://oklog.responseecho.com")
```

#### Why?
This inconvenience is due to [RedHat sunsetting OpenShift v2](https://blog.openshift.com/migrate-to-v3-v2-eol/), where ResponseEcho was hosted. Now it's hosted on Heroku.
The new custom domain will prevent these inconveniences to happen in the future.

#### What about existing URLs?
All the existing URLs generated by OkLog will still continue to work, as long as you change the host from `responseecho-simonpercic.rhcloud.com` to `oklog.responseecho.com`.

**Comment by jd-alexander** [comment]
Thank you for the update. Just noticed it.

**Comment by simonpercic** [comment]
Hi, thanks for updating. 👍 

Hopefully the new domain will prevent these inconveniences to happen in the future.
