### ISSUE TITLE
Last unit does not have enough valid bits

### ISSUE THREAD

**Issue by ka05** [simonpercic/OkLog#41]
No matter what i seem to be getting this error. I have tried various different JSON outputs.

**Comment by simonpercic** [comment]
Hi, are you able to provide more information about the issue you're facing?

I would suggest that you check if the generated link is split into multiple lines in logcat. If so, it's a [known limitation of Android's logging system](https://github.com/simonpercic/OkLog#known-limitations).

If you use Timber, the log output will be split into multiple lines. Then, you can manually copy both OkLog logcat lines into a single URL and open it in a browser.
