### ISSUE TITLE
Please publish to maven central

### ISSUE THREAD

**Issue by SteinerOk** [simonpercic/OkLog#44]
Currently, OkLog releases appear to only be published to jcenter and are not present on maven central. JCenter has a long history of artifact integrity issues and we try to avoid it at all costs. I recognize that maven central's publishing process is sometimes considered more tedious, but this signing/verification process is part of why it's preferred.

https://blog.autsoft.hu/a-confusing-dependency
https://twitter.com/jakewharton/status/1073102730443526144?lang=en

This has taken on some more immediacy due to the imminent shutdown of jcenter: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by simonpercic** [comment]
Hi,

OkLog [is now available](https://search.maven.org/search?q=com.github.simonpercic.oklog) on MavenCentral.

Closing the issue, thank you for raising it.
