### ISSUE TITLE
Feature request: Log for request body

### ISSUE THREAD

**Issue by blazsolar** [simonpercic/OkLog#9]
It would be nice to also have a link to body that you send up to server in POST, PUT,.. requests.

**Comment by simonpercic** [comment]
This has been implemented in version 2.0, along with a lot of other network data (incl. request url, method, content length, headers, response code, message, duration, size).

**Comment by ArthurSav** [comment]
Doesn't seem to log headers.
Edit: Nevermind, i did not set `.withRequestHeaders(true).withResponseHeaders(true)`

**Comment by simonpercic** [comment]
@ArthurSav OkLog is able to log both request and response headers, but both options are disabled by default. See [Additional log data options](https://github.com/simonpercic/OkLog#additional-log-data-options).

When building OkLogInterceptor with the Builder, you can use `withRequestHeaders(boolean)` and `withResponseHeaders(boolean)` to include headers, or use `withAllLogData()` to include all of the available log data.
